import * as vscode from 'vscode';
import * as z from 'zod/v4';

import {
    AnalyzeFrameTool,
    AnalyzeHotEventTool,
    DiffPipelineStateTool,
    FindDrawsByResourceIdTool,
    FindDrawsByShaderTool,
    FindDrawsByTextureTool,
    FindProjectImplementationTool,
    GetActionTimingsTool,
    GetBoundResourcesTool,
    GetBufferContentsTool,
    GetCaptureInfoTool,
    GetCurrentDrawPreviewTool,
    GetDrawCallsTool,
    GetEventChunksTool,
    GetEventDetailsTool,
    GetFrameSummaryTool,
    GetMeshDataTool,
    GetPassGraphTool,
    GetPipelineStateTool,
    GetReplayStatusTool,
    GetResourceDetailTool,
    GetResourcesTool,
    GetSelectionContextTool,
    GetShaderInfoTool,
    GetShaderSourceTool,
    GetTextureDataTool,
    GetTextureInfoTool,
    OpenCaptureTool,
    ListCaptureTargetsTool,
    LaunchRemoteApplicationTool,
    TriggerRemoteCaptureTool,
    CheckAndroidLaunchReadinessTool,
    LaunchWindowsApplicationTool,
    GetSessionStateTool,
    CloseSessionTool,
    CaptureFrameTool,
    DiagnoseEnvironmentTool,
    LaunchApplicationTool,
    GeneratePerformanceReportTool,
    ResourceMemoryAuditTool,
    CompareCapturesTool,
    FindShaderVariantsTool,
    CompareShadersTool,
    GetShaderCompileDiagnosticsTool,
    BuildEventBrowserContextTool,
    ValidateShaderEditTool,
    ApplyShaderEditTool,
    AddBookmarkTool,
    ListBookmarksTool,
    RemoveBookmarkTool,
    UpdateBookmarkTool,
    ExportInvestigationReportTool,
    WaitForLiveTargetTool,
    WaitForCaptureTool,
    ResourceLifetimeTool,
    FindUnusedResourcesTool,
    FindResourceLeaksTool,
    CompareResourceMemoryTool,
    CompareEventTimingsTool,
    TraceResourceUsageTool,
} from './tools';

export interface RenderDocToolDefinition {
    name: string;
    title: string;
    description: string;
    readOnly: boolean;
    inputSchema: z.ZodTypeAny;
    createTool: () => vscode.LanguageModelTool<any>;
}

export const RENDERDOC_TOOL_REGISTRY: readonly RenderDocToolDefinition[] = [
    {
        name: 'renderdoc_validateShaderEdit',
        title: 'Validate Shader Edit',
        description: 'Compile a proposed shader edit for diagnostics without applying or persisting the replacement.',
        readOnly: false,
        inputSchema: z.object({ resourceId: z.string().min(1), shaderStage: z.number().int(), sourceEncoding: z.number().int(), entryPoint: z.string().min(1), entryFileIndex: z.number().int().optional(), compileFlags: z.array(z.object({ name: z.string(), value: z.string() })).optional(), files: z.array(z.object({ filename: z.string().min(1), contents: z.string() })).min(1) }),
        createTool: () => new ValidateShaderEditTool(),
    },
    {
        name: 'renderdoc_applyShaderEdit',
        title: 'Apply Shader Edit',
        description: 'Apply a compiled shader replacement to the active replay session and re-run replay validation. This is a side-effecting operation and does not modify the RDC file.',
        readOnly: false,
        inputSchema: z.object({ resourceId: z.string().min(1), shaderStage: z.number().int(), sourceEncoding: z.number().int(), entryPoint: z.string().min(1), entryFileIndex: z.number().int().optional(), compileFlags: z.array(z.object({ name: z.string(), value: z.string() })).optional(), files: z.array(z.object({ filename: z.string().min(1), contents: z.string() })).min(1) }),
        createTool: () => new ApplyShaderEditTool(),
    },
    {
        name: 'renderdoc_buildEventBrowserContext',
        title: 'Build Event Browser Context',
        description: 'Filter RenderDoc events by marker, event range, operation type, duration, debug markers, empty operations, and text, then return a compact AI analysis context.',
        readOnly: true,
        inputSchema: z.object({ filter: z.string().optional(), markerFilter: z.string().optional(), excludeMarkers: z.boolean().optional(), onlyDrawCalls: z.boolean().optional(), eventIdMin: z.number().int().optional(), eventIdMax: z.number().int().optional(), sortByDuration: z.boolean().optional(), excludeDebugMarkers: z.boolean().optional(), excludeEmptyOperations: z.boolean().optional() }),
        createTool: () => new BuildEventBrowserContextTool(),
    },
    {
        name: 'renderdoc_getResourceLifetime',
        title: 'Get Resource Lifetime Evidence',
        description: 'Summarize available capture evidence for resource identity, footprint, and observed event scope without fabricating lifetime intervals.',
        readOnly: true,
        inputSchema: z.object({ resourceId: z.string().optional(), limit: z.number().int().min(1).max(500).optional() }),
        createTool: () => new ResourceLifetimeTool(),
    },
    {
        name: 'renderdoc_findUnusedResources',
        title: 'Find Unused Resources',
        description: 'Find conservative candidates with no direct usage evidence and clearly report the heuristic limitation.',
        readOnly: true,
        inputSchema: z.object({ limit: z.number().int().min(1).max(500).optional() }),
        createTool: () => new FindUnusedResourcesTool(),
    },
    {
        name: 'renderdoc_findResourceLeaks',
        title: 'Find Resource Leak Candidates',
        description: 'Compare two captures and identify persistent resource candidates, explicitly marked as low-confidence evidence rather than proof of a runtime leak.',
        readOnly: true,
        inputSchema: z.object({ baselinePath: z.string().min(1), candidatePath: z.string().min(1), limit: z.number().int().min(1).max(500).optional() }),
        createTool: () => new FindResourceLeaksTool(),
    },
    {
        name: 'renderdoc_compareResourceMemory',
        title: 'Compare Resource Memory',
        description: 'Compare RenderDoc resource byte-size footprints between two captures.',
        readOnly: true,
        inputSchema: z.object({ baselinePath: z.string().min(1), candidatePath: z.string().min(1), limit: z.number().int().min(1).max(500).optional() }),
        createTool: () => new CompareResourceMemoryTool(),
    },
    {
        name: 'renderdoc_compareEventTimings',
        title: 'Compare Event Timings',
        description: 'Compare timing values already present in two capture draw-call datasets without fabricating unavailable cross-capture replay timings.',
        readOnly: true,
        inputSchema: z.object({ baselinePath: z.string().min(1), candidatePath: z.string().min(1), limit: z.number().int().min(1).max(500).optional() }),
        createTool: () => new CompareEventTimingsTool(),
    },
    {
        name: 'renderdoc_waitForLiveTarget',
        title: 'Wait for RenderDoc Live Target',
        description: 'Wait until the current application session has a live RenderDoc target.',
        readOnly: true,
        inputSchema: z.object({ timeoutMs: z.number().int().min(100).max(60000).optional(), pollMs: z.number().int().min(50).max(2000).optional() }),
        createTool: () => new WaitForLiveTargetTool(),
    },
    {
        name: 'renderdoc_waitForCapture',
        title: 'Wait for RenderDoc Capture',
        description: 'Wait until the current session reports a completed capture.',
        readOnly: true,
        inputSchema: z.object({ timeoutMs: z.number().int().min(100).max(60000).optional(), pollMs: z.number().int().min(50).max(2000).optional() }),
        createTool: () => new WaitForCaptureTool(),
    },
    {
        name: 'renderdoc_addBookmark',
        title: 'Add RenderDoc Bookmark',
        description: 'Save an investigation bookmark for the current capture and optional event ID.',
        readOnly: false,
        inputSchema: z.object({ eventId: z.number().int().optional(), title: z.string().min(1), note: z.string().optional(), conclusion: z.string().optional(), analysis: z.string().optional(), screenshotPath: z.string().optional() }),
        createTool: () => new AddBookmarkTool(),
    },
    {
        name: 'renderdoc_listBookmarks',
        title: 'List RenderDoc Bookmarks',
        description: 'List saved RenderDoc investigation bookmarks.',
        readOnly: true,
        inputSchema: z.object({}),
        createTool: () => new ListBookmarksTool(),
    },
    {
        name: 'renderdoc_removeBookmark',
        title: 'Remove RenderDoc Bookmark',
        description: 'Remove one saved RenderDoc investigation bookmark by ID.',
        readOnly: false,
        inputSchema: z.object({ id: z.string().min(1) }),
        createTool: () => new RemoveBookmarkTool(),
    },
    {
        name: 'renderdoc_updateBookmark',
        title: 'Update RenderDoc Bookmark',
        description: 'Update the title, note, or event ID of a saved investigation bookmark.',
        readOnly: false,
        inputSchema: z.object({ id: z.string().min(1), title: z.string().min(1).optional(), note: z.string().optional(), eventId: z.number().int().optional(), conclusion: z.string().optional(), analysis: z.string().optional(), screenshotPath: z.string().optional() }),
        createTool: () => new UpdateBookmarkTool(),
    },
    {
        name: 'renderdoc_exportInvestigationReport',
        title: 'Export RenderDoc Investigation Report',
        description: 'Export a Markdown or JSON investigation report containing capture metadata, bookmarks, performance hotspots, and resource footprint.',
        readOnly: false,
        inputSchema: z.object({ format: z.enum(['markdown', 'json']).optional(), outputPath: z.string().optional(), timingLimit: z.number().int().min(1).max(200).optional() }),
        createTool: () => new ExportInvestigationReportTool(),
    },
    {
        name: 'renderdoc_findShaderVariants',
        title: 'Find Shader Variants',
        description: 'Find captured shader resources whose names or IDs match a shader query.',
        readOnly: true,
        inputSchema: z.object({ shaderName: z.string().min(1), limit: z.number().int().min(1).max(200).optional() }),
        createTool: () => new FindShaderVariantsTool(),
    },
    {
        name: 'renderdoc_compareShaders',
        title: 'Compare Shaders',
        description: 'Compare captured shader payloads between two events and report structural differences without claiming semantic equivalence.',
        readOnly: true,
        inputSchema: z.object({ leftEventId: z.number().int(), rightEventId: z.number().int(), stage: z.string().optional() }),
        createTool: () => new CompareShadersTool(),
    },
    {
        name: 'renderdoc_getShaderCompileDiagnostics',
        title: 'Get Shader Compile Diagnostics',
        description: 'Read captured shader compiler metadata, entry points, flags, and source availability for an event.',
        readOnly: true,
        inputSchema: z.object({ eventId: z.number().int(), stage: z.string().optional(), includeSource: z.boolean().optional() }),
        createTool: () => new GetShaderCompileDiagnosticsTool(),
    },
    {
        name: 'renderdoc_compareCaptures',
        title: 'Compare RenderDoc Captures',
        description: 'Compare two RDC files using capture metadata and resource footprint deltas.',
        readOnly: true,
        inputSchema: z.object({ baselinePath: z.string().min(1), candidatePath: z.string().min(1), limit: z.number().int().min(1).max(200).optional() }),
        createTool: () => new CompareCapturesTool(),
    },
    {
        name: 'renderdoc_resourceMemoryAudit',
        title: 'Resource Memory Audit',
        description: 'Rank captured resources by RenderDoc-reported byte size and summarize the capture resource footprint.',
        readOnly: true,
        inputSchema: z.object({ limit: z.number().int().min(1).max(200).optional() }),
        createTool: () => new ResourceMemoryAuditTool(),
    },
    {
        name: 'renderdoc_captureFrame',
        title: 'Capture Frame Workflow',
        description: 'Capture a frame from the active Windows or Android live session, save the RDC, and load it into the inspector.',
        readOnly: false,
        inputSchema: z.object({
            trigger: z.enum(['immediate', 'frame', 'delay']).optional(),
            frameNumber: z.number().int().nonnegative().optional(),
            delaySeconds: z.number().positive().optional(),
        }),
        createTool: () => new CaptureFrameTool(),
    },
    {
        name: 'renderdoc_diagnoseEnvironment',
        title: 'Diagnose RenderDoc Environment',
        description: 'Inspect native bridge, replay, MCP, adb, Android devices, and RenderDoc targets.',
        readOnly: true,
        inputSchema: z.object({ format: z.enum(['json', 'markdown']).optional(), outputPath: z.string().min(1).optional() }),
        createTool: () => new DiagnoseEnvironmentTool(),
    },
    {
        name: 'renderdoc_generatePerformanceReport',
        title: 'Generate Performance Report',
        description: 'Generate a concise evidence-based hotspot report from the current capture and GPU timings.',
        readOnly: true,
        inputSchema: z.object({ limit: z.number().int().min(1).max(200).optional(), format: z.enum(['json', 'markdown']).optional(), outputPath: z.string().min(1).optional() }),
        createTool: () => new GeneratePerformanceReportTool(),
    },
    {
        name: 'renderdoc_launchApplication',
        title: 'Launch Application Workflow',
        description: 'Launch a Windows executable or Android application. If platform is omitted, return a platform-required result instead of guessing.',
        readOnly: false,
        inputSchema: z.object({
            platform: z.enum(['windows', 'android']).optional(),
            app: z.string().min(1).describe('Windows .exe path or Android package/package/activity.'),
            targetUrl: z.string().optional(),
            targetQuery: z.string().optional(),
            workingDir: z.string().optional(),
            commandLine: z.string().optional(),
        }),
        createTool: () => new LaunchApplicationTool(),
    },
    {
        name: 'renderdoc_getSessionState',
        title: 'Get RenderDoc Session State',
        description: 'Read the active Windows or Android application session, launch phase, target, and latest capture.',
        readOnly: true,
        inputSchema: z.object({}),
        createTool: () => new GetSessionStateTool(),
    },
    {
        name: 'renderdoc_closeSession',
        title: 'Close RenderDoc Session',
        description: 'Disconnect the active application capture session without deleting saved captures.',
        readOnly: false,
        inputSchema: z.object({}),
        createTool: () => new CloseSessionTool(),
    },
    {
        name: 'renderdoc_checkAndroidLaunchReadiness',
        title: 'Check Android Launch Readiness',
        description: 'Check adb, Android device state, package installation, launcher activity, and RenderDoc target availability before launching an Android application.',
        readOnly: true,
        inputSchema: z.object({
            packageName: z.string().min(1),
            targetQuery: z.string().optional(),
        }),
        createTool: () => new CheckAndroidLaunchReadinessTool(),
    },
    {
        name: 'renderdoc_launchWindowsApplication',
        title: 'Launch Windows Application',
        description: 'Launch a Windows executable through RenderDoc and keep the live session for a later capture.',
        readOnly: false,
        inputSchema: z.object({
            executablePath: z.string().min(1).describe('Absolute path to a Windows .exe file.'),
            workingDir: z.string().optional(),
            commandLine: z.string().optional(),
        }),
        createTool: () => new LaunchWindowsApplicationTool(),
    },
    {
        name: 'renderdoc_listCaptureTargets',
        title: 'List Capture Targets',
        description: 'List connected remote RenderDoc targets that can launch Android applications.',
        readOnly: true,
        inputSchema: z.object({}),
        createTool: () => new ListCaptureTargetsTool(),
    },
    {
        name: 'renderdoc_launchRemoteApplication',
        title: 'Launch Remote Android Application',
        description: 'Launch an Android package/activity through a connected remote RenderDoc target and keep the live session active for a later capture.',
        readOnly: false,
        inputSchema: z.object({
            targetUrl: z.string().optional().describe('Exact RenderDoc target URL. Use this when the target is already known.'),
            targetQuery: z.string().optional().describe('Target name, id, or URL substring used to select one connected target when targetUrl is omitted.'),
            packageActivity: z.string().min(1).describe('Android package/activity, for example com.example.app/.MainActivity or a package name such as mobile.test.'),
            commandLine: z.string().optional().describe('Optional command-line arguments passed to the Android launch target.'),
        }),
        createTool: () => new LaunchRemoteApplicationTool(),
    },
    {
        name: 'renderdoc_triggerRemoteCapture',
        title: 'Capture Remote Frame',
        description: 'Trigger a frame capture from the currently active remote Android application, save the RDC locally, and load it into the VS Code inspector.',
        readOnly: false,
        inputSchema: z.object({
            trigger: z.enum(['immediate', 'frame', 'delay']).optional().describe('Capture mode. Defaults to immediate.'),
            frameNumber: z.number().int().optional().describe('Frame number for frame mode.'),
            delaySeconds: z.number().positive().optional().describe('Delay in seconds for delay mode.'),
        }),
        createTool: () => new TriggerRemoteCaptureTool(),
    },
    {
        name: 'renderdoc_openCapture',
        title: 'Resolve Or Open Capture',
        description: 'Resolve the active RenderDoc capture in this VS Code window when called with no filePath, or load a specific .rdc file when filePath is provided.',
        readOnly: false,
        inputSchema: z.object({
            filePath: z.string().optional().describe('Optional absolute path to a .rdc capture file. If omitted, resolves the active or open .rdc tab in this VS Code window.'),
        }),
        createTool: () => new OpenCaptureTool(),
    },
    {
        name: 'renderdoc_getCaptureInfo',
        title: 'Get Capture Info',
        description: 'Read metadata about the currently loaded RenderDoc capture.',
        readOnly: true,
        inputSchema: z.object({}),
        createTool: () => new GetCaptureInfoTool(),
    },
    {
        name: 'renderdoc_getDrawCalls',
        title: 'Get Draw Calls',
        description: 'List draw calls and marker hierarchy for the current capture.',
        readOnly: true,
        inputSchema: z.object({
            filter: z.string().optional().describe('Case-insensitive substring filter on draw call name.'),
            markerFilter: z.string().optional().describe('Only include events inside a marker group whose name contains this string (case-insensitive).'),
            excludeMarkers: z.boolean().optional().describe('If true, exclude marker/group nodes and return leaf events only.'),
            onlyDrawCalls: z.boolean().optional().describe('If true, only return actual GPU draw operations (Drawcall, Dispatch, MeshDispatch flags).'),
            eventIdMin: z.number().int().optional().describe('Only include events with eventId >= this value.'),
            eventIdMax: z.number().int().optional().describe('Only include events with eventId <= this value.'),
        }),
        createTool: () => new GetDrawCallsTool(),
    },
    {
        name: 'renderdoc_getActionTimings',
        title: 'Get Action Timings',
        description: 'Fetch GPU action timings for the current capture.',
        readOnly: true,
        inputSchema: z.object({
            eventIds: z.array(z.number().int()).optional().describe('Optional list of specific event IDs to query. If omitted, returns all matching leaf actions.'),
            markerFilter: z.string().optional().describe('Only include actions inside marker groups whose names contain this string (case-insensitive).'),
            excludeMarkers: z.array(z.string()).optional().describe('Exclude actions inside marker groups whose names contain any of these strings (case-insensitive).'),
            onlyDrawCalls: z.boolean().optional().describe('If true, only include actual draw/dispatch/mesh-dispatch leaf actions.'),
            limit: z.number().int().nonnegative().max(2000).optional().describe('Maximum timing rows to return. Default 200. Maximum 2000.'),
        }),
        createTool: () => new GetActionTimingsTool(),
    },
    {
        name: 'renderdoc_getResources',
        title: 'Get Resources',
        description: 'List GPU resources present in the current capture.',
        readOnly: true,
        inputSchema: z.object({
            type: z.string().optional().describe('Optional resource type filter: "Texture", "Buffer", or "Shader".'),
            limit: z.number().int().positive().max(500).optional().describe('Maximum entries to return. Default 500. Maximum 500.'),
            offset: z.number().int().nonnegative().optional().describe('Offset for pagination. Default 0.'),
        }),
        createTool: () => new GetResourcesTool(),
    },
    {
        name: 'renderdoc_getResourceDetail',
        title: 'Get Resource Detail',
        description: 'Read detail for one GPU resource by resource ID.',
        readOnly: true,
        inputSchema: z.object({
            resourceId: z.string().describe('The resource ID to look up.'),
        }),
        createTool: () => new GetResourceDetailTool(),
    },
    {
        name: 'renderdoc_getEventDetails',
        title: 'Get Event Details',
        description: 'Read detail for one draw call or GPU event by event ID.',
        readOnly: true,
        inputSchema: z.object({
            eventId: z.number().int().describe('The event ID (EID) to inspect.'),
        }),
        createTool: () => new GetEventDetailsTool(),
    },
    {
        name: 'renderdoc_getPipelineState',
        title: 'Get Pipeline State',
        description: 'Read the full GPU pipeline state for one event.',
        readOnly: true,
        inputSchema: z.object({
            eventId: z.number().int().describe('The event ID (EID) to get pipeline state for.'),
        }),
        createTool: () => new GetPipelineStateTool(),
    },
    {
        name: 'renderdoc_getShaderSource',
        title: 'Get Shader Source',
        description: 'Read shader source or disassembly for one event and stage.',
        readOnly: true,
        inputSchema: z.object({
            eventId: z.number().int().describe('The event ID (EID) to read shader source at.'),
            stage: z.string().optional().describe('Shader stage to read: "vertex", "fragment", "pixel", "geometry", "hull", "domain", or "compute". If omitted, returns all bound stages.'),
        }),
        createTool: () => new GetShaderSourceTool(),
    },
    {
        name: 'renderdoc_getShaderInfo',
        title: 'Get Shader Info',
        description: 'Read aggregated shader metadata, bindings, and constant buffers for one event.',
        readOnly: true,
        inputSchema: z.object({
            eventId: z.number().int().describe('The event ID (EID) to inspect shader info at.'),
            stage: z.string().optional().describe('Optional shader stage filter: "vertex", "fragment", "pixel", "geometry", "hull", "domain", "tessControl", "tessEval", or "compute". If omitted, returns all stages.'),
            includeSource: z.boolean().optional().describe('Include full source files or disassembly when available. Defaults to true when stage is specified.'),
            includeConstantBuffers: z.boolean().optional().describe('Include decoded constant buffer contents. Default true.'),
        }),
        createTool: () => new GetShaderInfoTool(),
    },
    {
        name: 'renderdoc_findProjectImplementation',
        title: 'Find Project Implementation',
        description: 'Search the open workspace for shader or pass implementation candidates related to the current capture.',
        readOnly: true,
        inputSchema: z.object({
            eventId: z.number().int().optional().describe('Optional event ID to derive shader names and pass/marker names from. Falls back to the focused inspector event if omitted.'),
            shaderName: z.string().optional().describe('Optional explicit shader name or shader file name to search in the workspace.'),
            passName: z.string().optional().describe('Optional explicit pass or marker name to search in C# project code.'),
            additionalTerms: z.array(z.string()).optional().describe('Additional free-form search terms to include in both shader and C# project searches.'),
            limit: z.number().int().positive().max(100).optional().describe('Maximum results to return per category. Default 12. Maximum 100.'),
        }),
        createTool: () => new FindProjectImplementationTool(),
    },
    {
        name: 'renderdoc_getTextureInfo',
        title: 'Get Texture Info',
        description: 'Read texture metadata for the current capture or a specific texture resource.',
        readOnly: true,
        inputSchema: z.object({
            textureId: z.string().optional().describe('Optional texture resource ID to filter by. If omitted, returns all textures in the capture.'),
        }),
        createTool: () => new GetTextureInfoTool(),
    },
    {
        name: 'renderdoc_analyzeFrame',
        title: 'Analyze Frame',
        description: 'Perform a broad performance-oriented analysis of the current frame capture.',
        readOnly: true,
        inputSchema: z.object({}),
        createTool: () => new AnalyzeFrameTool(),
    },
    {
        name: 'renderdoc_getSelectionContext',
        title: 'Get Selection Context',
        description: 'Read the current RenderDoc inspector focus and sidebar selection from this VS Code window.',
        readOnly: true,
        inputSchema: z.object({}),
        createTool: () => new GetSelectionContextTool(),
    },
    {
        name: 'renderdoc_getMeshData',
        title: 'Get Mesh Data',
        description: 'Read mesh data for one event and mesh stage, including topology, attributes, and sampled rows.',
        readOnly: true,
        inputSchema: z.object({
            eventId: z.number().int().describe('The event ID (EID) to read mesh data for.'),
            stage: z.enum(['vsin', 'vsout', 'gsout']).optional().describe('Mesh stage: "vsin" (vertex shader input), "vsout" (post-VS output), or "gsout" (post-GS output). Default "vsin".'),
            maxVertices: z.number().int().positive().max(4096).optional().describe('Maximum vertices to return in the sampled rows. Default 32. Maximum 4096.'),
            instance: z.number().int().nonnegative().optional().describe('Instance index for instanced draws. Default 0.'),
        }),
        createTool: () => new GetMeshDataTool(),
    },
    {
        name: 'renderdoc_getFrameSummary',
        title: 'Get Frame Summary',
        description: 'Return a concise overview of frame structure, passes, and capture statistics.',
        readOnly: true,
        inputSchema: z.object({}),
        createTool: () => new GetFrameSummaryTool(),
    },
    {
        name: 'renderdoc_findDrawsByShader',
        title: 'Find Draws by Shader',
        description: 'Reverse-search draw calls that use a shader name or entry-point substring.',
        readOnly: true,
        inputSchema: z.object({
            shaderName: z.string().describe('Shader name or entry point substring to search (case-insensitive).'),
        }),
        createTool: () => new FindDrawsByShaderTool(),
    },
    {
        name: 'renderdoc_findDrawsByTexture',
        title: 'Find Draws by Texture',
        description: 'Reverse-search draw calls that sample a texture name substring.',
        readOnly: true,
        inputSchema: z.object({
            textureName: z.string().describe('Texture name substring to search (case-insensitive).'),
        }),
        createTool: () => new FindDrawsByTextureTool(),
    },
    {
        name: 'renderdoc_findDrawsByResourceId',
        title: 'Find Draws by Resource ID',
        description: 'Reverse-search draw calls that bind a specific resource ID.',
        readOnly: true,
        inputSchema: z.object({
            resourceId: z.string().describe('Resource ID string to find (exact match).'),
        }),
        createTool: () => new FindDrawsByResourceIdTool(),
    },
    {
        name: 'renderdoc_getTextureData',
        title: 'Get Texture Data',
        description: 'Sample texture pixel data for a resource, mip level, and optional event.',
        readOnly: true,
        inputSchema: z.object({
            textureId: z.string().describe('Resource ID of the texture to sample.'),
            mip: z.number().int().optional().describe('Mip level to sample. 0 = full resolution. Default 0.'),
            eventId: z.number().int().optional().describe('Event ID at which to sample the texture. 0 = end of frame. Default 0.'),
            channelExtract: z.number().int().optional().describe('Channel to extract: -1 = all RGBA, 0 = R, 1 = G, 2 = B, 3 = A. Default -1.'),
        }),
        createTool: () => new GetTextureDataTool(),
    },
    {
        name: 'renderdoc_getBufferContents',
        title: 'Get Buffer Contents',
        description: 'Read a bounded byte range from a GPU buffer resource.',
        readOnly: true,
        inputSchema: z.object({
            resourceId: z.string().describe('Resource ID of the GPU buffer to read.'),
            offset: z.number().int().nonnegative().optional().describe('Byte offset into the buffer. Default 0.'),
            len: z.number().int().positive().max(65536).optional().describe('Number of bytes to read. Default 4096. Maximum 65536.'),
            eventId: z.number().int().optional().describe('Event ID at which to read the buffer. 0 = end of frame. Default 0.'),
        }),
        createTool: () => new GetBufferContentsTool(),
    },
    {
        name: 'renderdoc_getReplayStatus',
        title: 'Get Replay Status',
        description: 'Query the current replay state and available capabilities. Use this before calling replay-dependent tools to avoid errors.',
        readOnly: true,
        inputSchema: z.object({}),
        createTool: () => new GetReplayStatusTool(),
    },
    {
        name: 'renderdoc_getBoundResources',
        title: 'Get Bound Resources',
        description: 'Get a normalized summary of resources bound at a given event, including render targets, textures, buffers, samplers, and constant buffers.',
        readOnly: true,
        inputSchema: z.object({
            eventId: z.number().int().describe('The event ID (EID) to inspect bound resources at.'),
            includeUnused: z.boolean().optional().describe('If false, filter out resources marked as statically unused by the shader. Default true (include all).'),
            includeConstantBuffers: z.boolean().optional().describe('Include constant buffer metadata in the output. Default true.'),
        }),
        createTool: () => new GetBoundResourcesTool(),
    },
    {
        name: 'renderdoc_getEventChunks',
        title: 'Get Event Chunks',
        description: 'Get the API-level event chunks (draw calls, state changes) for a specific event ID.',
        readOnly: true,
        inputSchema: z.object({
            eventId: z.number().int().describe('The event ID (EID) to get API-level chunks for.'),
        }),
        createTool: () => new GetEventChunksTool(),
    },
    {
        name: 'renderdoc_getCurrentDrawPreview',
        title: 'Get Current Draw Preview',
        description: 'Get a preview image of the current draw call output at a specific event ID.',
        readOnly: true,
        inputSchema: z.object({
            eventId: z.number().int().describe('The event ID (EID) to render a preview for.'),
            channelExtract: z.number().int().optional().describe('Channel to extract: -1 = all RGBA, 0 = R, 1 = G, 2 = B, 3 = A. Default -1.'),
            overlayMode: z.string().optional().describe('Overlay mode for the preview. Default "none".'),
            resourceId: z.string().optional().describe('Optional resource ID to preview a specific render target.'),
            overlayResourceId: z.string().optional().describe('Optional resource ID for overlay comparison.'),
        }),
        createTool: () => new GetCurrentDrawPreviewTool(),
    },
    {
        name: 'renderdoc_traceResourceUsage',
        title: 'Trace Resource Usage',
        description: 'Trace how a resource is used across the frame, identifying producers (writes) and consumers (reads).',
        readOnly: true,
        inputSchema: z.object({
            resourceId: z.string().describe('The resource ID to trace usage for across the frame.'),
            maxEvents: z.number().int().positive().max(500).optional().describe('Maximum number of usage events to return per category. Default 50. Maximum 500.'),
        }),
        createTool: () => new TraceResourceUsageTool(),
    },
    {
        name: 'renderdoc_diffPipelineState',
        title: 'Diff Pipeline State',
        description: 'Compare pipeline state between two events and identify differences in shaders, render targets, and state.',
        readOnly: true,
        inputSchema: z.object({
            eventIdA: z.number().int().describe('The first event ID (EID) to compare.'),
            eventIdB: z.number().int().describe('The second event ID (EID) to compare against.'),
        }),
        createTool: () => new DiffPipelineStateTool(),
    },
    {
        name: 'renderdoc_analyzeHotEvent',
        title: 'Analyze Hot Event',
        description: 'Perform comprehensive analysis of a hot event including timing, pipeline state, resources, and optional shader/mesh data.',
        readOnly: true,
        inputSchema: z.object({
            eventId: z.number().int().describe('The event ID (EID) of the hot event to analyze.'),
            includeShaderInfo: z.boolean().optional().describe('Include structured shader metadata (stage, name, binding counts). Default true.'),
            includeMeshData: z.boolean().optional().describe('Include mesh topology and vertex attribute summary. Default false.'),
        }),
        createTool: () => new AnalyzeHotEventTool(),
    },
    {
        name: 'renderdoc_getPassGraph',
        title: 'Get Pass Graph',
        description: 'Build a graph of render passes from the draw call hierarchy, including timing and resource usage.',
        readOnly: true,
        inputSchema: z.object({
            includeResources: z.boolean().optional().describe('If true, collect render target and sampled texture resource IDs per pass for dependency edge computation. Default true.'),
        }),
        createTool: () => new GetPassGraphTool(),
    },
];
